### ISSUE TITLE
style footer

### ISSUE THREAD

**Issue by nicomq** [scdantilles/angole-theme#1]
![image](https://cloud.githubusercontent.com/assets/10815686/12277003/7010cf06-b94f-11e5-8561-83d895f51d83.png)
- changer la typo des entrées de 2d niveau : Helvetica Neue _light_ => en tt cas qq chose de plus light
- changer la couleur on hover : pas blanc, un cran plus sombre => cf bandeau menu haut de page
- traits de séparation entre les colonnes, cf invisionapp

**Comment by kivutar** [comment]
Fait.
