### ISSUE TITLE
home - btn-white

### ISSUE THREAD

**Issue by nicomq** [scdantilles/angole-theme#4]
Sur la home page peux-tu tester 
.btn-white {
  color: white;
  border-radius: 2px;
  border-color: rgba(29, 134, 153, 0.5);
  background-color: rgba(40, 175, 205, 0.8);
  box-shadow: 0 3px 5px rgba(29, 134, 153, 0.5);
  padding: 5px 20px;
}
Et éventuellement renommer btn-white en autre chose s'il n'est plus blanc?

**Comment by kivutar** [comment]
Fait.
